"""add domain to organisations

Revision ID: 389ad425d824
Revises: e6815fb1d80c
Create Date: 2026-05-23 09:15:30.781549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389ad425d824'
down_revision: Union[str, Sequence[str], None] = 'e6815fb1d80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('domain', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'domain')
    # ### end Alembic commands ###
