"""add unique constraint on org_id and email in employees

Revision ID: 8fc6ef11e8bb
Revises: 389ad425d824
Create Date: 2026-05-23 09:35:10.095304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc6ef11e8bb'
down_revision: Union[str, Sequence[str], None] = '389ad425d824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_org_email', 'employees', ['org_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_org_email', 'employees', type_='unique')
    # ### end Alembic commands ###
